Version 1.0.1
Twispay/OpenCart3.0 pull request #1
Opened 2019-09-03 05:21 UTC by cosminbosutar

Version of that replaces the POST form with a codified JSON, solves security issues and has subscription support integrated.

2019-09-04 18:16 UTC, dragos-ursu requested changes
Please see the comments.

2019-09-04 18:16 UTC, dragos-ursu commented on upload/system/helper/Twispay_Status_Updater.php
> +         * @param object decrypted: Decrypted order message.
The $decrypted parameter seem to always be sent as an array and not an object.

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +        $data =json_decode(json_encode($data), TRUE);
Is there a reason for this? In the code there are only calls that pass an array as the $data parameter.

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +                unset($data[$key]);
There is no further usage of the $data variable that would make use of unsetting a key at this point.

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +    public function logTransaction($data, $overwrite = FALSE)
Can't find any usage of this method, it is needed?

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +        $order_recurring_id = $order_recurring['order_recurring_id'];
Can't find any usage of $order_recurring_id, it is needed?

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +                unset($data[$key]);
There is no reason to unset $data[$key] at this point.

2019-09-04 18:16 UTC, dragos-ursu commented on upload/catalog/model/extension/payment/twispay_recurring.php
> +        $data = json_decode(json_encode($data), TRUE);
Any reason to have this here? Seem like $data is always sent as an array.

2019-09-08 21:50 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +        $data =json_decode(json_encode($data), TRUE);
There was a case when $data was an object so json_decode(json_encode($data), TRUE); was converting it to an associative array. But its not needed anymore. I've removed it.

2019-09-08 21:52 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +                unset($data[$key]);
Fixed

2019-09-08 21:52 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +    public function logTransaction($data, $overwrite = FALSE)
Is not needed anymode. I've removed it.

2019-09-08 21:53 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +        $order_recurring_id = $order_recurring['order_recurring_id'];
Removed.

2019-09-08 21:54 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_transaction.php
> +                unset($data[$key]);
Fixed.

2019-09-08 22:04 UTC, MichaelRotaru commented on upload/catalog/model/extension/payment/twispay_recurring.php
> +        $data = json_decode(json_encode($data), TRUE);
Fixed.

2019-09-08 22:19 UTC, MichaelRotaru commented on upload/system/helper/Twispay_Status_Updater.php
> +         * @param object decrypted: Decrypted order message.
Fixed.

2019-09-24 09:30 UTC, merged