Installer fixes
Twispay/OpenCart3.0 pull request #2
Opened 2019-10-14 16:23 UTC by cosminbosutar

Moved api to extension folders.
Fixed security check based on user_token instead of api_id.
Fix customer identifier filter issue.

2019-10-31 13:42 UTC, dragos-ursu requested changes
Please check the comments.

2019-10-31 13:42 UTC, dragos-ursu commented on README.md
> +2. Use the Opencart 3 Extension Installer and upload the OCmod ar
Please review the description on this line.

2019-10-31 13:42 UTC, dragos-ursu commented on README.md
> +7. Select **No** under **Test Mode**. _(Unless you are tesing)_
Please correct typo `tesing`.

2019-10-31 13:42 UTC, dragos-ursu commented on README.md
> +[github]: https://github.com/MichaelRotaru/OpenCart3.0
Please link to `https://github.com/Twispay/OpenCart3.0`.

2019-11-04 07:34 UTC, cosminbosutar commented on README.md
> +2. Use the Opencart 3 Extension Installer and upload the OCmod ar
Done

2019-11-04 07:34 UTC, cosminbosutar commented on README.md
> +7. Select **No** under **Test Mode**. _(Unless you are tesing)_
Done

2019-11-04 07:34 UTC, cosminbosutar commented on README.md
> +[github]: https://github.com/MichaelRotaru/OpenCart3.0
Done

2019-11-06 11:56 UTC, dragos-ursu approved these changes
Code review done

2020-02-06 16:12 UTC, merged